[package]
name = "rust-lld-repro"
version = "0.1.0"
authors = ["Maia Fox <m.fox@f5.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
